version: "3.6"

services:

# chia farming
  chia.local:
    hostname: chia
    #image: ghcr.io/chia-network/chia:latest
    image: pnupong/dk-chia:1.2.5
    volumes:
      - "/volume1/general/chia/chiahome:/root"
      - "/volume1/general/chia/plots:/plots"
      - "/volumeUSB1/usbshare/chia/plots:/plotsusb1"
      - "/volumeUSB2/usbshare/chia/plots:/plotsusb2"
      - "/volumeUSB3/usbshare/chia/plots:/plotsusb3"
      - "/volumeUSB4/usbshare/chia/plots:/plotsusb4"
      - "/volumeUSB5/usbshare/chia/plots:/plotsusb5"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      keys: ""
      TZ: "America/Chicago"
    restart: always
    deploy:
      resources:
        limits:
          memory: 4g
          # cpus: '1'
    logging:
      driver: syslog

# chia plotter
  chia-plot.local:
    hostname: chia-plot
    image: ghcr.io/chia-network/chia:latest
    volumes:
      - "/volume1/general/chia/chiahome:/root"
      - "/volume1/general/chia/plots:/plots"
      - "/etc/localtime:/etc/localtime:ro"
      - "/volume2/chiatemp/00tmp:/plots00tmp"
      - "/volume2/chiatemp/00logs:/plots00logs"
    environment:
       keys: ""
       TZ: "America/Chicago"
    #restart: always
    entrypoint: ""
    deploy:
      resources:
        limits:
          memory: 4g
    logging:
      driver: syslog
